In [1]:
#import required libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LinearRegression

#Fetch Dataset
dataset = pd.read_csv('bike_sharing.csv')

#Get independent features
X = dataset[['temp']].values
print(X)

#Get dependent features
Y = dataset[['cnt']].values
print(Y)

[[ 0.24]
 [ 0.22]
 [ 0.22]
 ..., 
 [ 0.26]
 [ 0.26]
 [ 0.26]]
[[16]
 [40]
 [32]
 ..., 
 [90]
 [61]
 [49]]


In [2]:
#Splitting dataset into train and test set

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 1/3, random_state = 0)

print('X_train -> ', X_train)
print('X_test -> ', X_test)
print('Y_train -> ', Y_train)
print('Y_test -> ', Y_test)

X_train ->  [[ 0.84]
 [ 0.58]
 [ 0.86]
 ..., 
 [ 0.24]
 [ 0.42]
 [ 0.64]]
X_test ->  [[ 0.56]
 [ 0.44]
 [ 0.44]
 ..., 
 [ 0.44]
 [ 0.28]
 [ 0.4 ]]
Y_train ->  [[243]
 [183]
 [494]
 ..., 
 [  6]
 [ 69]
 [530]]
Y_test ->  [[  7]
 [  5]
 [743]
 ..., 
 [155]
 [137]
 [154]]


In [3]:
#Build the model

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

pred = regressor.predict(X_test)
print(pred)

[[ 212.65232843]
 [ 167.53719989]
 [ 167.53719989]
 ..., 
 [ 167.53719989]
 [ 107.38369517]
 [ 152.49882371]]


In [4]:
#Plot the model (Training data)
plt.title('SLR to predict no. of bikes getting shared based on the temp of the day ')
plt.scatter(X_train, Y_train, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.xlabel('Temperature')
plt.ylabel('Count of bikes')
plt.show()

In [33]:
#Plot the model (Test data)
plt.title('SLR to predict no. of bikes getting shared based on the temp of the day ')
plt.scatter(X_test, Y_test, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.xlabel('Temperature')
plt.ylabel('Count of bikes')
plt.show()